### ISSUE TITLE
Bug in Administrative Offices

### ISSUE THREAD

**Issue by kamicut** [ParametricPress/01-flatland-follies-an-adjunct-simulator#3]
When all the options in the administrative offices are selected once (https://github.com/ParametricPress/01-flatland-follies-an-adjunct-simulator/blob/master/index.idyll#L975-L1005) the next time the player chooses "Administrative Offices" they get to a prompt but cannot select anything to go back

**Comment by mathisonian** [comment]
Thanks for pointing this out @kamicut - I will work on a fix
